import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';



List<IconData> accountIcons = [
  FontAwesomeIcons.wallet,
    FontAwesomeIcons.creditCard,
    FontAwesomeIcons.moneyBill,
    FontAwesomeIcons.piggyBank,
    FontAwesomeIcons.briefcase,
    FontAwesomeIcons.coins,
    FontAwesomeIcons.fileInvoiceDollar,
    FontAwesomeIcons.moneyCheck,
    FontAwesomeIcons.moneyBill1Wave,
    FontAwesomeIcons.receipt,
    FontAwesomeIcons.scaleBalanced,
    FontAwesomeIcons.commentDollar,
    FontAwesomeIcons.circleDollarToSlot,
    FontAwesomeIcons.bitcoinSign,
    FontAwesomeIcons.dollarSign,
    FontAwesomeIcons.yenSign,
    FontAwesomeIcons.turkishLiraSign,
    FontAwesomeIcons.tengeSign,
    FontAwesomeIcons.sterlingSign,
    FontAwesomeIcons.rupeeSign,
    FontAwesomeIcons.rupiahSign,
    FontAwesomeIcons.euroSign,
    FontAwesomeIcons.australSign,
    FontAwesomeIcons.bangladeshiTakaSign,
    FontAwesomeIcons.cediSign,
    FontAwesomeIcons.liraSign,
    FontAwesomeIcons.handHoldingDollar,
    FontAwesomeIcons.percent,
    FontAwesomeIcons.chartLine,
    FontAwesomeIcons.chartPie,
    FontAwesomeIcons.userTie,
    FontAwesomeIcons.buildingColumns,
    FontAwesomeIcons.circleUser,
    FontAwesomeIcons.userSecret,
    FontAwesomeIcons.paypal,
    FontAwesomeIcons.amazonPay,
    FontAwesomeIcons.ccApplePay,
    FontAwesomeIcons.idCardClip,
    FontAwesomeIcons.squarePollVertical,
    FontAwesomeIcons.registered,
    FontAwesomeIcons.globe,
    FontAwesomeIcons.award,
    FontAwesomeIcons.dove,
];
