// Colors

import 'package:flutter/material.dart';

const List<Color> mainColors = [
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.orange,
  Colors.purple,
  Colors.teal,
  Colors.indigo,
];
final List<Color> colors = [
  Colors.red.shade800,
  Colors.red.shade600,
  Colors.red,
  Colors.red.shade400,
  Colors.red.shade200,
  Colors.blue.shade800,
  Colors.blue.shade600,
  Colors.blue,
  Colors.blue.shade400,
  Colors.blue.shade200,
  Colors.green.shade800,
  Colors.green.shade600,
  Colors.green,
  Colors.green.shade400,
  Colors.green.shade200,
  Colors.yellow.shade800,
  Colors.yellow.shade600,
  Colors.yellow,
  Colors.yellow.shade400,
  Colors.yellow.shade200,
  Colors.orange.shade800,
  Colors.orange.shade600,
  Colors.orange,  Colors.orange.shade400,
  Colors.orange.shade200,
  Colors.purple.shade800,
  Colors.purple.shade600,
  Colors.purple,  Colors.purple.shade400,
  Colors.purple.shade200,
  Colors.teal.shade800,
  Colors.teal.shade600,
  Colors.teal,  Colors.teal.shade400,
  Colors.teal.shade200,
  Colors.pink.shade800,
  Colors.pink.shade600,
  Colors.pink,  Colors.pink.shade400,
  Colors.pink.shade200,
  Colors.indigo.shade800,
  Colors.indigo.shade600,
  Colors.indigo,  Colors.indigo.shade400,
  Colors.indigo.shade200,
  Colors.amber.shade800,
  Colors.amber.shade600,
  Colors.amber,  Colors.amber.shade400,
  Colors.amber.shade200,
  Colors.black,
  Colors.black87,
  Colors.black54,  Colors.black45,
  Colors.black38,
];
