
// Colors

import 'package:flutter/material.dart';

final List<Color> colors = [ 
  Colors.red,
  Colors.red.shade800,
  Colors.red.shade600,
  Colors.red.shade400,
  Colors.red.shade200,
  Colors.blue,
  Colors.blue.shade800,
  Colors.blue.shade600,
  Colors.blue.shade400,
  Colors.blue.shade200,
  Colors.green,
  Colors.green.shade800,
  Colors.green.shade600,
  Colors.green.shade400,
  Colors.green.shade200,
  Colors.yellow,
  Colors.yellow.shade800,
  Colors.yellow.shade600,
  Colors.yellow.shade400,
  Colors.yellow.shade200,
  Colors.orange,
  Colors.orange.shade800,
  Colors.orange.shade600,
  Colors.orange.shade400,
  Colors.orange.shade200,
  Colors.purple,
  Colors.purple.shade800,
  Colors.purple.shade600,
  Colors.purple.shade400,
  Colors.purple.shade200,
  Colors.teal,
  Colors.teal.shade800,
  Colors.teal.shade600,
  Colors.teal.shade400,
  Colors.teal.shade200,
  Colors.pink,
  Colors.pink.shade800,
  Colors.pink.shade600,
  Colors.pink.shade400,
  Colors.pink.shade200,
  Colors.indigo,
  Colors.indigo.shade800,
  Colors.indigo.shade600,
  Colors.indigo.shade400,
  Colors.indigo.shade200,
  Colors.amber,
  Colors.amber.shade800,
  Colors.amber.shade600,
  Colors.amber.shade400,
  Colors.amber.shade200,
];

