
import '../features/data/models/currency/currency_model.dart';

 List<CurrencyModel> currencies = [
    CurrencyModel(
        code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ'),
    CurrencyModel(code: 'AFN', name: 'Afghan Afghani', symbol: '؋'),
    CurrencyModel(code: 'ALL', name: 'Albanian Lek', symbol: 'L'),
    CurrencyModel(code: 'AMD', name: 'Armenian Dram', symbol: '֏'),
    CurrencyModel(
        code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ'),
    CurrencyModel(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz'),
    CurrencyModel(code: 'ARS', name: 'Argentine Peso', symbol: '\$'),
    CurrencyModel(code: 'AUD', name: 'Australian Dollar', symbol: '\$'),
    CurrencyModel(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ'),
    CurrencyModel(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼'),
    CurrencyModel(
        code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM'),
    CurrencyModel(code: 'BBD', name: 'Barbadian Dollar', symbol: '\$'),
    CurrencyModel(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳'),
    CurrencyModel(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв'),
    CurrencyModel(code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب'),
    CurrencyModel(code: 'BIF', name: 'Burundian Franc', symbol: 'FBu'),
    CurrencyModel(code: 'BMD', name: 'Bermudan Dollar', symbol: '\$'),
    CurrencyModel(code: 'BND', name: 'Brunei Dollar', symbol: '\$'),
    CurrencyModel(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.'),
    CurrencyModel(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$'),
    CurrencyModel(code: 'BSD', name: 'Bahamian Dollar', symbol: '\$'),
    CurrencyModel(code: 'BTC', name: 'Bitcoin', symbol: '₿'),
    CurrencyModel(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.'),
    CurrencyModel(code: 'BWP', name: 'Botswanan Pula', symbol: 'P'),
    CurrencyModel(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br'),
    CurrencyModel(code: 'BZD', name: 'Belize Dollar', symbol: '\$'),
    CurrencyModel(code: 'CAD', name: 'Canadian Dollar', symbol: '\$'),
    CurrencyModel(code: 'CDF', name: 'Congolese Franc', symbol: 'FC'),
    CurrencyModel(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF'),
    CurrencyModel(
        code: 'CLF', name: 'Chilean Unit of Account (UF)', symbol: 'UF'),
    CurrencyModel(code: 'CLP', name: 'Chilean Peso', symbol: '\$'),
    CurrencyModel(code: 'CNH', name: 'Chinese Yuan (Offshore)', symbol: 'CNH'),
    CurrencyModel(code: 'CNY', name: 'Chinese Yuan', symbol: '¥'),
    CurrencyModel(code: 'COP', name: 'Colombian Peso', symbol: '\$'),
    CurrencyModel(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡'),
    CurrencyModel(code: 'CUC', name: 'Cuban Convertible Peso', symbol: 'CUC'),
    CurrencyModel(code: 'CUP', name: 'Cuban Peso', symbol: '₱'),
    CurrencyModel(code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc'),
    CurrencyModel(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč'),
    CurrencyModel(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj'),
    CurrencyModel(code: 'DKK', name: 'Danish Krone', symbol: 'kr'),
    CurrencyModel(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$'),
    CurrencyModel(code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج'),
    CurrencyModel(code: 'EGP', name: 'Egyptian Pound', symbol: '£'),
    CurrencyModel(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk'),
    CurrencyModel(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br'),
    CurrencyModel(code: 'EUR', name: 'Euro', symbol: '€'),
    CurrencyModel(code: 'FJD', name: 'Fijian Dollar', symbol: '\$'),
    CurrencyModel(code: 'FKP', name: 'Falkland Islands Pound', symbol: '£'),
    CurrencyModel(code: 'GBP', name: 'British Pound Sterling', symbol: '£'),
    CurrencyModel(code: 'GEL', name: 'Georgian Lari', symbol: '₾'),
    CurrencyModel(code: 'GGP', name: 'Guernsey Pound', symbol: '£'),
    CurrencyModel(code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵'),
    CurrencyModel(code: 'GIP', name: 'Gibraltar Pound', symbol: '£'),
    CurrencyModel(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D'),
    CurrencyModel(code: 'GNF', name: 'Guinean Franc', symbol: 'FG'),
    CurrencyModel(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q'),
    CurrencyModel(code: 'GYD', name: 'Guyanaese Dollar', symbol: '\$'),
    CurrencyModel(code: 'HKD', name: 'Hong Kong Dollar', symbol: '\$'),
    CurrencyModel(code: 'HNL', name: 'Honduran Lempira', symbol: 'L'),
    CurrencyModel(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn'),
    CurrencyModel(code: 'HTG', name: 'Haitian Gourde', symbol: 'G'),
    CurrencyModel(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft'),
    CurrencyModel(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp'),
    CurrencyModel(code: 'ILS', name: 'Israeli New Shekel', symbol: '₪'),
    CurrencyModel(code: 'IMP', name: 'Manx pound', symbol: '£'),
    CurrencyModel(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
    CurrencyModel(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د'),
    CurrencyModel(code: 'IRR', name: 'Iranian Rial', symbol: '﷼'),
    CurrencyModel(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr'),
    CurrencyModel(code: 'JEP', name: 'Jersey Pound', symbol: '£'),
    CurrencyModel(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$'),
    CurrencyModel(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD'),
    CurrencyModel(code: 'JPY', name: 'Japanese Yen', symbol: '¥'),
    CurrencyModel(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh'),
    CurrencyModel(code: 'KGS', name: 'Kyrgystani Som', symbol: 'с'),
    CurrencyModel(code: 'KHR', name: 'Cambodian Riel', symbol: '៛'),
    CurrencyModel(code: 'KMF', name: 'Comorian Franc', symbol: 'CF'),
    CurrencyModel(code: 'KPW', name: 'North Korean Won', symbol: '₩'),
    CurrencyModel(code: 'KRW', name: 'South Korean Won', symbol: '₩'),
    CurrencyModel(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD'),
    CurrencyModel(code: 'KYD', name: 'Cayman Islands Dollar', symbol: '\$'),
    CurrencyModel(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸'),
    CurrencyModel(code: 'LAK', name: 'Laotian Kip', symbol: '₭'),
    CurrencyModel(code: 'LBP', name: 'Lebanese Pound', symbol: '£'),
    CurrencyModel(code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨'),
    CurrencyModel(code: 'LRD', name: 'Liberian Dollar', symbol: '\$'),
    CurrencyModel(code: 'LSL', name: 'Lesotho Loti', symbol: 'L'),
    CurrencyModel(code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د'),
    CurrencyModel(code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.'),
    CurrencyModel(code: 'MDL', name: 'Moldovan Leu', symbol: 'L'),
    CurrencyModel(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar'),
    CurrencyModel(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден'),
    CurrencyModel(code: 'MMK', name: 'Myanma Kyat', symbol: 'K'),
    CurrencyModel(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮'),
    CurrencyModel(code: 'MOP', name: 'Macanese Pataca', symbol: 'P'),
    CurrencyModel(code: 'MRO', name: 'Mauritanian Ouguiya', symbol: 'UM'),
    CurrencyModel(code: 'MUR', name: 'Mauritian Rupee', symbol: '₨'),
    CurrencyModel(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'ރ.'),
    CurrencyModel(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK'),
    CurrencyModel(code: 'MXN', name: 'Mexican Peso', symbol: '\$'),
    CurrencyModel(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM'),
    CurrencyModel(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT'),
    CurrencyModel(code: 'NAD', name: 'Namibian Dollar', symbol: '\$'),
    CurrencyModel(code: 'NGN', name: 'Nigerian Naira', symbol: '₦'),
    CurrencyModel(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$'),
    CurrencyModel(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr'),
    CurrencyModel(code: 'NPR', name: 'Nepalese Rupee', symbol: '₨'),
    CurrencyModel(code: 'NZD', name: 'New Zealand Dollar', symbol: '\$'),
    CurrencyModel(code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.'),
    CurrencyModel(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.'),
    CurrencyModel(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.'),
    CurrencyModel(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K'),
    CurrencyModel(code: 'PHP', name: 'Philippine Peso', symbol: '₱'),
    CurrencyModel(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨'),
    CurrencyModel(code: 'PLN', name: 'Polish Złoty', symbol: 'zł'),
    CurrencyModel(code: 'PYG', name: 'Paraguayan Guarani', symbol: 'Gs'),
    CurrencyModel(code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق'),
    CurrencyModel(code: 'RON', name: 'Romanian Leu', symbol: 'lei'),
    CurrencyModel(code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.'),
    CurrencyModel(code: 'RUB', name: 'Russian Ruble', symbol: '₽'),
    CurrencyModel(code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw'),
    CurrencyModel(code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س'),
    CurrencyModel(code: 'SBD', name: 'Solomon Islands Dollar', symbol: '\$'),
    CurrencyModel(code: 'SCR', name: 'Seychellois Rupee', symbol: '₨'),
    CurrencyModel(code: 'SDG', name: 'Sudanese Pound', symbol: '£'),
    CurrencyModel(code: 'SEK', name: 'Swedish Krona', symbol: 'kr'),
    CurrencyModel(code: 'SGD', name: 'Singapore Dollar', symbol: '\$'),
    CurrencyModel(code: 'SHP', name: 'Saint Helena Pound', symbol: '£'),
    CurrencyModel(code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le'),
    CurrencyModel(code: 'SOS', name: 'Somali Shilling', symbol: 'S'),
    CurrencyModel(code: 'SRD', name: 'Surinamese Dollar', symbol: '\$'),
    CurrencyModel(code: 'SSP', name: 'South Sudanese Pound', symbol: '£'),
    CurrencyModel(
        code: 'STD', name: 'São Tomé and Príncipe Dobra', symbol: 'Db'),
    CurrencyModel(code: 'SVC', name: 'Salvadoran Colón', symbol: '\$'),
    CurrencyModel(code: 'SYP', name: 'Syrian Pound', symbol: '£'),
    CurrencyModel(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L'),
    CurrencyModel(code: 'THB', name: 'Thai Baht', symbol: '฿'),
    CurrencyModel(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM'),
    CurrencyModel(code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T'),
    CurrencyModel(code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت'),
    CurrencyModel(code: 'TOP', name: 'Tongan Pa\'anga', symbol: 'T\$'),
    CurrencyModel(code: 'TRY', name: 'Turkish Lira', symbol: '₺'),
    CurrencyModel(
        code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT\$'),
    CurrencyModel(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT\$'),
    CurrencyModel(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh'),
    CurrencyModel(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴'),
    CurrencyModel(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh'),
    CurrencyModel(code: 'USD', name: 'United States Dollar', symbol: '\$'),
    CurrencyModel(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$U'),
    CurrencyModel(code: 'UZS', name: 'Uzbekistan Som', symbol: 'лв'),
    CurrencyModel(code: 'VEF', name: 'Venezuelan Bolívar', symbol: 'Bs'),
    CurrencyModel(code: 'VND', name: 'Vietnamese Dong', symbol: '₫'),
    CurrencyModel(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT'),
    CurrencyModel(code: 'WST', name: 'Samoan Tala', symbol: 'T'),
    CurrencyModel(code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA'),
    CurrencyModel(code: 'XAG', name: 'Silver Ounce', symbol: 'XAG'),
    CurrencyModel(code: 'XAU', name: 'Gold Ounce', symbol: 'XAU'),
    CurrencyModel(code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC\$'),
    CurrencyModel(code: 'XDR', name: 'Special Drawing Rights', symbol: 'XDR'),
    CurrencyModel(code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA'),
    CurrencyModel(code: 'XPD', name: 'Palladium Ounce', symbol: 'XPD'),
    CurrencyModel(code: 'XPF', name: 'CFP Franc', symbol: 'CFPF'),
    CurrencyModel(code: 'XPT', name: 'Platinum Ounce', symbol: 'XPT'),
    CurrencyModel(code: 'YER', name: 'Yemeni Rial', symbol: '﷼'),
    CurrencyModel(code: 'ZAR', name: 'South African Rand', symbol: 'R'),
    CurrencyModel(
        code: 'ZMK', name: 'Zambian Kwacha (1968–2012)', symbol: 'ZK'),
    CurrencyModel(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZMW'),
    CurrencyModel(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'ZWL'),
  ];
